### ISSUE TITLE
Supervisor not letting  go to sleep

### ISSUE THREAD

**Issue by SeaSlugLabs** [balenablocks/finabler#27]
When executing 
curl -X POST localhost:1337/sleep/120/160

I get supervisor busy

supervisor busy...
05.07.21 09:17:45 (-0500)  finabler  Error registering sleep command: Device is not Idle, likely updating, will not shutdown
05.07.21 09:17:45 (-0500)  finabler  Error: Device is not Idle, likely updating, will not shutdown
05.07.21 09:17:45 (-0500)  finabler      at /usr/src/app/index.js:152:15
05.07.21 09:17:45 (-0500)  finabler      at processTicksAndRejections (internal/process/task_queues.js:97:5)

when I restart the service i get

finabler  Firmata version set to v2.0.1
05.07.21 09:20:29 (-0500)  finabler  Firmware already downloaded. Skipping.
05.07.21 09:20:34 (-0500)  finabler  setting fin-status tag to awake...
05.07.21 09:20:34 (-0500)  finabler  setting wake-eta tag to N/A...
05.07.21 09:20:34 (-0500)  finabler  balenaFin revision 11
05.07.21 09:20:34 (-0500)  finabler  server listening on port 1337
05.07.21 09:20:34 (-0500)  finabler  setting fin-version tag to v1.1.1...
05.07.21 09:20:34 (-0500)  finabler  supervisor busy...
05.07.21 09:20:35 (-0500)  finabler  Error: cannot reach supervisor
05.07.21 09:20:35 (-0500)  finabler      at /usr/src/app/index.js:134:17
05.07.21 09:20:35 (-0500)  finabler      at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by phil-d-wilson** [comment]
This is not actually an issue with the finabler. The block will not attempt to flash a firmware, or sleep a device, unless it knows the device is not doing anything important like updating the application. The supervisor needs to report the state as "idle" for the finabler to proceed.

In this case the supervisor was in an invalid state with multiple references to an application service. Deleting the references removed the issue and the Fin slept OK.
