### ISSUE TITLE
Update API calls from V1 endpoints

### ISSUE THREAD

**Issue by phil-d-wilson** [balenablocks/finabler#28]
Either move to the latest endpoint, or since we are already bringing in the SDK into the block, change to using that instead

Opinion @Bucknalla ?

**Comment by Bucknalla** [comment]
@phil-d-wilson yeah I think we just standardise using the SDK if we're already using it

**Comment by Bucknalla** [comment]
@phil-d-wilson I was talking with Carlo and he's been actually working in the background to fix this for some of the QA work he's been doing for the Fin so he will be pushing a branch shortly that addresses a bunch of things. It should also be ES6 compliant so it'll be super easy to take what I started working on for the TS rewrite and apply that as well.

**Comment by phil-d-wilson** [comment]
Sounds great @Bucknalla ! I'm happy to contribute to the TS work.

**Comment by curcuz** [comment]
@phil-d-wilson @Bucknalla WIP PR here https://github.com/balenablocks/finabler/pull/29

**Comment by mehalter** [comment]
@phil-d-wilson @Bucknalla was this resolved with #31 since that took place of #29 in a reorganization?

**Comment by curcuz** [comment]
@mehalter yes!
